-- ============================================================================
-- AtmoSync Snowflake Architecture: 03 - ANALYTICS Layer (Star Schema & CDC)
-- ============================================================================

USE DATABASE ATMOSYNC_DB;
USE SCHEMA ANALYTICS_SCHEMA;

-- 1. Dimension Tables
CREATE OR REPLACE TABLE DIM_CONTAINER (
    CONTAINER_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    CONTAINER_ID VARCHAR(32) NOT NULL UNIQUE,
    REEFER_MODEL VARCHAR(50),
    MANUFACTURER VARCHAR(50),
    CAPACITY_CU_M FLOAT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_COMMODITY (
    COMMODITY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    COMMODITY_NAME VARCHAR(50) NOT NULL UNIQUE,
    OPTIMUM_TEMP_C FLOAT,
    MIN_TEMP_C FLOAT,
    MAX_TEMP_C FLOAT,
    OPTIMUM_HUMIDITY_PCT FLOAT,
    BASE_SHELF_LIFE_DAYS NUMBER,
    ACTIVATION_ENERGY_KJ FLOAT
);

CREATE OR REPLACE TABLE DIM_LOCATION (
    LOCATION_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    LOCATION_NAME VARCHAR(100) NOT NULL UNIQUE,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    PORT_CODE VARCHAR(10),
    COUNTRY VARCHAR(50)
);

-- 2. Fact Tables
CREATE OR REPLACE TABLE FCT_TELEMETRY (
    TELEMETRY_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    RECORDED_AT TIMESTAMP_NTZ NOT NULL,
    CONTAINER_ID VARCHAR(32) NOT NULL,
    COMMODITY_NAME VARCHAR(50),
    TEMPERATURE_CELSIUS FLOAT,
    HUMIDITY_PERCENT FLOAT,
    DOOR_OPEN_STATUS BOOLEAN,
    GPS_SPEED_KMH FLOAT,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    SPOT_MARKET_PRICE FLOAT
)
CLUSTER BY (RECORDED_AT::DATE, CONTAINER_ID);

CREATE OR REPLACE TABLE FCT_SPOILAGE_ALERTS (
    ALERT_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    ALERT_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONTAINER_ID VARCHAR(32) NOT NULL,
    COMMODITY_NAME VARCHAR(50),
    ARRHENIUS_DECAY_RATIO FLOAT,
    REMAINING_SHELF_LIFE_HOURS FLOAT,
    FRESHNESS_INDEX_PCT FLOAT,
    SPOILAGE_RISK_SCORE_PCT FLOAT,
    SEVERITY VARCHAR(20)
);

CREATE OR REPLACE TABLE FCT_ARBITRAGE_OPPORTUNITIES (
    ARBITRAGE_KEY NUMBER AUTOINCREMENT PRIMARY KEY,
    EVALUATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONTAINER_ID VARCHAR(32) NOT NULL,
    ORIGINAL_PORT VARCHAR(100),
    RECOMMENDED_PORT VARCHAR(100),
    NET_PROFIT_GAIN_USD FLOAT,
    CARGO_SAVED_METRIC_TONS FLOAT,
    ACTION_STATUS VARCHAR(32) DEFAULT 'RECOMMENDED'
);

-- 3. Snowflake Stream for Real-time CDC (Change Data Capture)
CREATE OR REPLACE STREAM STREAM_RAW_TELEMETRY ON TABLE ATMOSYNC_DB.RAW_SCHEMA.RAW_TELEMETRY;

-- 4. Snowflake Task to Automatically Process Incoming Telemetry Stream Every 5 Minutes
CREATE OR REPLACE TASK TASK_PROCESS_TELEMETRY_STREAM
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('STREAM_RAW_TELEMETRY')
AS
    INSERT INTO FCT_TELEMETRY (RECORDED_AT, CONTAINER_ID, COMMODITY_NAME, TEMPERATURE_CELSIUS, HUMIDITY_PERCENT, DOOR_OPEN_STATUS, GPS_SPEED_KMH, LATITUDE, LONGITUDE, SPOT_MARKET_PRICE)
    SELECT
        PAYLOAD:timestamp::TIMESTAMP_NTZ,
        PAYLOAD:container_id::VARCHAR(32),
        PAYLOAD:commodity::VARCHAR(50),
        PAYLOAD:temperature::FLOAT,
        PAYLOAD:humidity::FLOAT,
        PAYLOAD:door_open::BOOLEAN,
        PAYLOAD:gps_speed_kmh::FLOAT,
        PAYLOAD:latitude::FLOAT,
        PAYLOAD:longitude::FLOAT,
        PAYLOAD:market_price::FLOAT
    FROM STREAM_RAW_TELEMETRY;

-- Enable Task
-- ALTER TASK TASK_PROCESS_TELEMETRY_STREAM RESUME;
