-- ============================================================================
-- AtmoSync Snowflake Architecture: 04 - RBAC Security & Access Control
-- ============================================================================

USE ROLE ACCOUNTADMIN;

-- 1. Create Functional Roles
CREATE ROLE IF NOT EXISTS ATMOSYNC_SYSADMIN;
CREATE ROLE IF NOT EXISTS ATMOSYNC_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS ATMOSYNC_DATA_SCIENTIST;
CREATE ROLE IF NOT EXISTS ATMOSYNC_ANALYST;
CREATE ROLE IF NOT EXISTS ATMOSYNC_READONLY;

-- 2. Role Hierarchy
GRANT ROLE ATMOSYNC_READONLY TO ROLE ATMOSYNC_ANALYST;
GRANT ROLE ATMOSYNC_ANALYST TO ROLE ATMOSYNC_DATA_SCIENTIST;
GRANT ROLE ATMOSYNC_DATA_SCIENTIST TO ROLE ATMOSYNC_DATA_ENGINEER;
GRANT ROLE ATMOSYNC_DATA_ENGINEER TO ROLE ATMOSYNC_SYSADMIN;
GRANT ROLE ATMOSYNC_SYSADMIN TO ROLE SYSADMIN;

-- 3. Database & Schema Grants
GRANT USAGE ON DATABASE ATMOSYNC_DB TO ROLE ATMOSYNC_READONLY;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ATMOSYNC_DB TO ROLE ATMOSYNC_READONLY;

-- Read-Only Privileges for Analysts
GRANT SELECT ON ALL TABLES IN SCHEMA ATMOSYNC_DB.ANALYTICS_SCHEMA TO ROLE ATMOSYNC_READONLY;
GRANT SELECT ON ALL VIEWS IN SCHEMA ATMOSYNC_DB.ANALYTICS_SCHEMA TO ROLE ATMOSYNC_READONLY;

-- Data Engineer Privileges for ETL Management
GRANT ALL PRIVILEGES ON DATABASE ATMOSYNC_DB TO ROLE ATMOSYNC_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ATMOSYNC_DB TO ROLE ATMOSYNC_DATA_ENGINEER;

-- 4. Data Masking Policy for Sensitive Geolocation / Driver Info
CREATE OR REPLACE MASKING POLICY MASK_EXACT_LOCATION AS (val FLOAT) RETURNS FLOAT ->
  CASE
    WHEN CURRENT_ROLE() IN ('ATMOSYNC_SYSADMIN', 'ATMOSYNC_DATA_ENGINEER') THEN val
    ELSE ROUND(val, 1) -- Obfuscate precise GPS coordinates for lower privilege roles
  END;

-- Apply Masking Policy
ALTER TABLE ATMOSYNC_DB.ANALYTICS_SCHEMA.FCT_TELEMETRY 
MODIFY COLUMN LATITUDE SET MASKING POLICY MASK_EXACT_LOCATION;

ALTER TABLE ATMOSYNC_DB.ANALYTICS_SCHEMA.FCT_TELEMETRY 
MODIFY COLUMN LONGITUDE SET MASKING POLICY MASK_EXACT_LOCATION;
