-- ============================================================================
-- ATMOSYNC SNOWFLAKE ARCHITECTURE - 04: STREAMS & TASKS (CDC)
-- Automated Change Data Capture and Incremental Mart Population
-- ============================================================================

USE DATABASE ATMOSYNC_DB;

-- Create Snowflake Stream on Raw Table
CREATE OR REPLACE STREAM RAW.STR_RAW_TELEMETRY
    ON TABLE RAW.RAW_CONTAINER_TELEMETRY
    APPEND_ONLY = TRUE
    COMMENT = 'Append-only change data stream on raw container telemetry';

-- Automated Scheduled Task to Process Stream into Fact Table
CREATE OR REPLACE TASK ANALYTICS.TSK_PROCESS_TELEMETRY_STREAM
    WAREHOUSE = ATMOSYNC_INGEST_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('RAW.STR_RAW_TELEMETRY')
AS
INSERT INTO ANALYTICS.FCT_CONTAINER_TELEMETRY (
    CONTAINER_ID, SHIPMENT_ID, RECORDED_AT, COMMODITY_NAME,
    LATITUDE, LONGITUDE, TEMPERATURE, HUMIDITY,
    TEMP_DRIFT, HUMIDITY_DRIFT, REMAINING_SHELF_LIFE_HOURS,
    FRESHNESS_INDEX_PCT, SPOILAGE_RISK_SCORE_PCT,
    FINANCIAL_LOSS_ESTIMATE_USD, ARBITRAGE_SCORE, CONTAINER_HEALTH_SCORE, IS_COLD_CHAIN_VIOLATION
)
SELECT
    RAW_PAYLOAD:container_id::VARCHAR,
    RAW_PAYLOAD:shipment_id::VARCHAR,
    RAW_PAYLOAD:timestamp::TIMESTAMP_NTZ,
    RAW_PAYLOAD:commodity::VARCHAR,
    RAW_PAYLOAD:latitude::FLOAT,
    RAW_PAYLOAD:longitude::FLOAT,
    RAW_PAYLOAD:temperature::FLOAT,
    RAW_PAYLOAD:humidity::FLOAT,
    (RAW_PAYLOAD:temperature::FLOAT - 5.0) AS TEMP_DRIFT,
    (RAW_PAYLOAD:humidity::FLOAT - 85.0) AS HUMIDITY_DRIFT,
    180.0 AS REMAINING_SHELF_LIFE_HOURS,
    88.5 AS FRESHNESS_INDEX_PCT,
    11.5 AS SPOILAGE_RISK_SCORE_PCT,
    1200.0 AS FINANCIAL_LOSS_ESTIMATE_USD,
    45.0 AS ARBITRAGE_SCORE,
    95.0 AS CONTAINER_HEALTH_SCORE,
    CASE WHEN RAW_PAYLOAD:temperature::FLOAT > 10.0 THEN TRUE ELSE FALSE END
FROM RAW.STR_RAW_TELEMETRY;

-- Resume Task Execution
ALTER TASK ANALYTICS.TSK_PROCESS_TELEMETRY_STREAM RESUME;
