-- ============================================================================
-- ATMOSYNC SNOWFLAKE ARCHITECTURE - 05: RBAC & SECURITY
-- Grants Least Privilege Roles for Engineers, Analysts, and API Service
-- ============================================================================

USE ROLE SECURITYADMIN;

-- 1. Create Roles
CREATE ROLE IF NOT EXISTS ATMOSYNC_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS ATMOSYNC_ANALYST;
CREATE ROLE IF NOT EXISTS ATMOSYNC_API_SERVICE;

USE ROLE SYSADMIN;

-- Grant Database & Warehouse Usage
GRANT USAGE ON DATABASE ATMOSYNC_DB TO ROLE ATMOSYNC_DATA_ENGINEER;
GRANT USAGE ON DATABASE ATMOSYNC_DB TO ROLE ATMOSYNC_ANALYST;
GRANT USAGE ON DATABASE ATMOSYNC_DB TO ROLE ATMOSYNC_API_SERVICE;

GRANT USAGE ON WAREHOUSE ATMOSYNC_INGEST_WH TO ROLE ATMOSYNC_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE ATMOSYNC_ANALYTICS_WH TO ROLE ATMOSYNC_ANALYST;
GRANT USAGE ON WAREHOUSE ATMOSYNC_ANALYTICS_WH TO ROLE ATMOSYNC_API_SERVICE;

-- Schema Level Grants
GRANT ALL PRIVILEGES ON SCHEMA ATMOSYNC_DB.RAW TO ROLE ATMOSYNC_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA ATMOSYNC_DB.STAGING TO ROLE ATMOSYNC_DATA_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA ATMOSYNC_DB.ANALYTICS TO ROLE ATMOSYNC_DATA_ENGINEER;

-- Analyst & API Read-Only Grants
GRANT USAGE ON SCHEMA ATMOSYNC_DB.ANALYTICS TO ROLE ATMOSYNC_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ATMOSYNC_DB.ANALYTICS TO ROLE ATMOSYNC_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA ATMOSYNC_DB.ANALYTICS TO ROLE ATMOSYNC_ANALYST;

GRANT USAGE ON SCHEMA ATMOSYNC_DB.ANALYTICS TO ROLE ATMOSYNC_API_SERVICE;
GRANT SELECT ON ALL TABLES IN SCHEMA ATMOSYNC_DB.ANALYTICS TO ROLE ATMOSYNC_API_SERVICE;

COMMENT ON ROLE ATMOSYNC_DATA_ENGINEER IS 'Full DDL/DML access for ETL pipelines';
COMMENT ON ROLE ATMOSYNC_ANALYST IS 'Read-only access for BI reporting';
